### ISSUE TITLE
White screen issue

### ISSUE THREAD

**Issue by mswartz** [Gaboze-Pocaio/Round-1#1]
Hi there, I assembled my Round 1 board over the weekend and am having trouble getting past the white screen on the embedded display. I followed your guide and tested the board, reflowed the battery board things, but still no luck. If I plug in an hdmi cable and monitor it works fine, just can't get the display on the board to work. What do you reckon?

**Comment by mswartz** [comment]
Doing some more testing, it appears the buttons on the board don't work either. If I plug in a keyboard and an hdmi monitor, it boots into retropie and regognizes my usb keyboard. But it does not recognize button presses or do anything on the screen but display a white screen. Is the board faulty? The Pi and software seem fine.

**Comment by negativ72rus** [comment]
Hello!
I ran into a similar problem, what could be wrong?

**Comment by mswartz** [comment]
No idea. I had 2 that were having the exact same problem. He replied and sent me a link to his official firmware, which fixed one of them, but the other is still WSODed. Haven't heard back from him about why that might be. @32teeth: any ideas?

**Comment by negativ72rus** [comment]
> No idea. I had 2 that were having the exact same problem. He replied and sent me a link to his official firmware, which fixed one of them, but the other is still WSODed. Haven't heard back from him about why that might be. @32teeth: any ideas?

@mswartz Can you share a link to the firmware? from the repository of the first round, they missed where they went.

**Comment by 32teeth** [comment]
[Downloads Site](http://gameboy.32teeth.org/)
